//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _0515.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCourse
    {
        public System.Guid ID { get; set; }
        public System.Guid StudentID { get; set; }
        public System.Guid CourseID { get; set; }
        public System.DateTime ModifiedDT { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Student Student { get; set; }
    }
}
